// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: protobufs/hello.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - hello.Greeter

/// Namespace containing generated types for the "hello.Greeter" service.
internal enum Hello_Greeter {
    /// Service descriptor for the "hello.Greeter" service.
    internal static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "hello.Greeter")
    /// Namespace for method metadata.
    internal enum Method {
        /// Namespace for "SayHello" metadata.
        internal enum SayHello {
            /// Request type for "SayHello".
            internal typealias Input = Hello_HelloRequest
            /// Response type for "SayHello".
            internal typealias Output = Hello_HelloResponse
            /// Descriptor for "SayHello".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "hello.Greeter"),
                method: "SayHello"
            )
        }
        /// Descriptors for all methods in the "hello.Greeter" service.
        internal static let descriptors: [GRPCCore.MethodDescriptor] = [
            SayHello.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "hello.Greeter" service.
    internal static let hello_Greeter = GRPCCore.ServiceDescriptor(fullyQualifiedService: "hello.Greeter")
}

// MARK: hello.Greeter (server)

extension Hello_Greeter {
    /// Streaming variant of the service protocol for the "hello.Greeter" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    internal protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "SayHello" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Hello_HelloRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Hello_HelloResponse` messages.
        func sayHello(
            request: GRPCCore.StreamingServerRequest<Hello_HelloRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Hello_HelloResponse>
    }

    /// Service protocol for the "hello.Greeter" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    internal protocol ServiceProtocol: Hello_Greeter.StreamingServiceProtocol {
        /// Handle the "SayHello" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Hello_HelloRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Hello_HelloResponse` message.
        func sayHello(
            request: GRPCCore.ServerRequest<Hello_HelloRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Hello_HelloResponse>
    }

    /// Simple service protocol for the "hello.Greeter" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    internal protocol SimpleServiceProtocol: Hello_Greeter.ServiceProtocol {
        /// Handle the "SayHello" method.
        ///
        /// - Parameters:
        ///   - request: A `Hello_HelloRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Hello_HelloResponse` to respond with.
        func sayHello(
            request: Hello_HelloRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Hello_HelloResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
extension Hello_Greeter.StreamingServiceProtocol {
    internal func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Hello_Greeter.Method.SayHello.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Hello_HelloRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Hello_HelloResponse>(),
            handler: { request, context in
                try await self.sayHello(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
extension Hello_Greeter.ServiceProtocol {
    internal func sayHello(
        request: GRPCCore.StreamingServerRequest<Hello_HelloRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Hello_HelloResponse> {
        let response = try await self.sayHello(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
extension Hello_Greeter.SimpleServiceProtocol {
    internal func sayHello(
        request: GRPCCore.ServerRequest<Hello_HelloRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Hello_HelloResponse> {
        return GRPCCore.ServerResponse<Hello_HelloResponse>(
            message: try await self.sayHello(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: hello.Greeter (client)

extension Hello_Greeter {
    /// Generated client protocol for the "hello.Greeter" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    internal protocol ClientProtocol: Sendable {
        /// Call the "SayHello" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Hello_HelloRequest` message.
        ///   - serializer: A serializer for `Hello_HelloRequest` messages.
        ///   - deserializer: A deserializer for `Hello_HelloResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func sayHello<Result>(
            request: GRPCCore.ClientRequest<Hello_HelloRequest>,
            serializer: some GRPCCore.MessageSerializer<Hello_HelloRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Hello_HelloResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Hello_HelloResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "hello.Greeter" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    internal struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        internal init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "SayHello" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Hello_HelloRequest` message.
        ///   - serializer: A serializer for `Hello_HelloRequest` messages.
        ///   - deserializer: A deserializer for `Hello_HelloResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func sayHello<Result>(
            request: GRPCCore.ClientRequest<Hello_HelloRequest>,
            serializer: some GRPCCore.MessageSerializer<Hello_HelloRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Hello_HelloResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Hello_HelloResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Hello_Greeter.Method.SayHello.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension Hello_Greeter.ClientProtocol {
    /// Call the "SayHello" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Hello_HelloRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func sayHello<Result>(
        request: GRPCCore.ClientRequest<Hello_HelloRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Hello_HelloResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.sayHello(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Hello_HelloRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Hello_HelloResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension Hello_Greeter.ClientProtocol {
    /// Call the "SayHello" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func sayHello<Result>(
        _ message: Hello_HelloRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Hello_HelloResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Hello_HelloRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.sayHello(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}